version: '3'

services:
  app:
    environment:
      - STORAGE_DIR
      - LOGGING_LEVEL
    volumes:
      - .${STORAGE_DIR}:${STORAGE_DIR}
    command: python server.py
    build:
      context: ./app
    ports:
      - "8080:8080"
