version: '3'

services:
  app:
    volumes:
      - ./test_photos:/test_photos
    env_file:
      - app/.env
    command: python server.py
    build:
      context: ./app
    ports:
      - "8080:8080"
